CREATE DATABASE IF NOT EXISTS onebyone;
USE ONEBYONE;
CREATE TABLE IF NOT EXISTS frases (
frase_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
frase VARCHAR(255) NOT NULL,
autor VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS frasesUsuario (
frase_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
fraseUsuario VARCHAR(255) NOT NULL,
autorUsuario VARCHAR(255) NOT NULL,
fecha DATE
);
INSERT INTO frases (frase, autor) VALUES
('El único modo de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs'),
('No te preocupes por los fracasos, preocúpate por las posibilidades que pierdes cuando ni siquiera lo intentas.', 'Jack Canfield'),
('La única manera de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs'),
('La mejor manera de predecir el futuro es crearlo.', 'Peter Drucker'),
('El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito.', 'Albert Schweitzer'),
('El único lugar donde el éxito viene antes que el trabajo es en el diccionario.', 'Vidal Sassoon'),
('Haz hoy lo que otros no quieren, haz mañana lo que otros no pueden.', 'Jerry Rice'),
('El éxito no es definitivo, el fracaso no es fatal: es el coraje para continuar lo que cuenta.', 'Winston Churchill'),
('El secreto para salir adelante es comenzar.', 'Mark Twain'),
('El único límite para nuestro logro de mañana será nuestras dudas de hoy.', 'Franklin D. Roosevelt'),
('No importa cuántas veces hayas fallado, seguir adelante es lo único que importa.', 'Winston Churchill'),
('Nuestro mayor miedo no es que seamos inadecuados. Nuestro miedo más profundo es que somos poderosos más allá de toda medida.', 'Marianne Williamson'),
('La vida es 10% lo que nos sucede y 90% cómo reaccionamos ante ello.', 'Charles R. Swindoll'),
('El éxito es la suma de pequeños esfuerzos repetidos un día tras otro.', 'Robert Collier'),
('No cuentes los días, haz que los días cuenten.', 'Muhammad Ali'),
('No importa lo lento que vayas, siempre y cuando no te detengas.', 'Confucio'),
('La disciplina es el puente entre metas y logros.', 'Jim Rohn'),
('No hay ascensor hacia el éxito, debes tomar las escaleras.', 'Zig Ziglar'),
('La mejor manera de predecir el futuro es crearlo.', 'Peter Drucker'),
('Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.', 'Maya Angelou'),
('Cree que puedes y estás a medio camino.', 'Theodore Roosevelt'),
('El éxito no es el final, el fracaso no es fatal: es el coraje de continuar lo que cuenta.', 'Winston Churchill'),
('Tu tiempo es limitado, no lo malgastes viviendo la vida de otra persona.', 'Steve Jobs'),
('No se trata de tener tiempo, se trata de hacer tiempo.', 'Unknown'),
('Hoy es el día más importante de tu vida.', 'W. Clement Stone'),
('La mejor venganza es un éxito masivo.', 'Frank Sinatra'),
('Lo que se obtiene con violencia, solamente se puede mantener con violencia.', 'Mahatma Gandhi'),
('No puedes tener una vida positiva y una mente negativa.', 'Joyce Meyer'),
('Haz que cada día cuente.', 'Steve Maraboli'),
('El éxito es aprender a ir de fracaso en fracaso sin desesperarse.', 'Winston Churchill'),
('Nunca es tarde para ser lo que podrías haber sido.', 'George Eliot'),
('No eres derrotado cuando pierdes, eres derrotado cuando te rindes.', 'Paulo Coelho'),
('Haz que tu vida sea un sueño y que ese sueño sea realidad.', 'Antoine de Saint-Exupéry'),
('Lo que se logra con esfuerzo, vale la pena tenerlo.', 'Friedrich Nietzsche'),
('Atrévete a vivir la vida de tus sueños.', 'Unknown'),
('Tu vida solo mejora cuando tú mejoras.', 'Unknown'),
('La mente es todo. Lo que piensas, te conviertes.', 'Buda'),
('La diferencia entre una persona exitosa y otras no es la falta de fuerza, no la falta de conocimiento, sino la falta de voluntad.', 'Vince Lombardi'),
('La vida es lo que pasa mientras estás ocupado haciendo otros planes.', 'Allen Saunders'),
('Haz que la elección refleje tus esperanzas, no tus miedos.', 'Nelson Mandela'),
('No dejes que lo que no puedes hacer interfiera con lo que puedes hacer.', 'John Wooden'),
('Hoy es un buen día para empezar.', 'Unknown'),
('La única manera de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs'),
('El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito.', 'Albert Schweitzer'),
('La única manera de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs'),
('La mejor manera de predecir el futuro es crearlo.', 'Peter Drucker'),
('El éxito no es definitivo, el fracaso no es fatal: es el coraje para continuar lo que cuenta.', 'Winston Churchill'),
('El secreto para salir adelante es comenzar.', 'Mark Twain'),
('El único límite para nuestro logro de mañana será nuestras dudas de hoy.', 'Franklin D. Roosevelt'),
('No importa cuántas veces hayas fallado, seguir adelante es lo único que importa.', 'Winston Churchill'),
('Nuestro mayor miedo no es que seamos inadecuados. Nuestro miedo más profundo es que somos poderosos más allá de toda medida.', 'Marianne Williamson');
